config/routes.rb
Rails.application.routes.draw do
  get "ping", to: "ping#index"
  get "up" => "rails/health#show", as: :rails_health_check

  resource :request, only: %i[new update create] do
    get "/back", to: "requests#back"
  end

  get "subject" => "requests#edit"
  get "subject-name" => "requests#edit"
  get "subject-date-of-birth" => "requests#edit"
  get "subject-relationship" => "requests#edit"
  get "solicitor-details" => "requests#edit"
  get "requester-details" => "requests#edit"
  get "letter-of-consent" => "requests#edit"
  get "letter-of-consent-check" => "requests#edit"
  get "requester-id" => "requests#edit"
  get "requester-address" => "requests#edit"
  get "requester-id-check" => "requests#edit"
  get "subject-id" => "requests#edit"
  get "subject-address" => "requests#edit"
  get "subject-id-check" => "requests#edit"

  get "moj" => "requests#edit"
  get "prison-location" => "requests#edit"
  get "prison-number" => "requests#edit"
  get "prison-information" => "requests#edit"
  get "prison-dates" => "requests#edit"

  get "probation-location" => "requests#edit"
  get "probation-information" => "requests#edit"
  get "probation-dates" => "requests#edit"

  get "laa" => "requests#edit"
  get "laa-dates" => "requests#edit"
  get "opg" => "requests#edit"
  get "opg-dates" => "requests#edit"
  get "other-where" => "requests#edit"
  get "other" => "requests#edit"
  get "other-dates" => "requests#edit"

  get "contact-address" => "requests#edit"
  get "contact-email" => "requests#edit"
  get "upcoming" => "requests#edit"

  get "check-answers" => "requests#show"
  get "form-sent" => "requests#complete"

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unprocessable_entity"
  get "/500", to: "errors#internal_error"

  get "cookies/:consent" => "cookies#update"
  post "cookies" => "cookies#update"
  get "cookies" => "pages#cookie_consent", as: "cookies_consent"

  get "accessibility" => "pages#accessibility", as: "accessibility"
  get "privacy" => "pages#privacy", as: "privacy"

  root to: "pages#homepage"

  if Rails.env.test?
    namespace :test do
      resource :session, only: %i[create]
    end
  end
end

app/views/pages/accessibility.html.erb
<% title t(".page_title") %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>

    <p class="govuk-body">This accessibility statement applies to the Request personal information form at: <%= govuk_link_to "https://request-personal-info.form.service.justice.gov.uk" %>.</p>
    <p class="govuk-body">This form was built by the Ministry of Justice. Justice Digital is responsible for the content of this form.</p>
    <h2 class="govuk-heading-m">Using this form</h2>
    <p class="govuk-body">We want as many people as possible to be able to use this form. For example, that means you should be able to:</p>
    <%= govuk_list ["change colours, contrast levels and fonts",
                    "zoom in up to 300% without the text spilling off the screen",
                    "navigate the form using just a keyboard",
                    "navigate the form using speech recognition software",
                    "listen to the form using a screen reader (including recent versions of JAWS, NVDA and VoiceOver)"], type: :bullet %>

    <p class="govuk-body">We have also made the text as simple as possible to understand.</p>
    <p class="govuk-body"><%= govuk_link_to "AbilityNet", "https://mcmw.abilitynet.org.uk/" %> has advice on making your device easier to use if you have a disability.</p>

    <h2 class="govuk-heading-m">How accessible this form is</h2>
    <p class="govuk-body">We have performed a basic accessibility check of this form and believe it meets the <%= govuk_link_to "Web Content Accessibility Guidelines version 2.2 AA standard", "https://www.w3.org/TR/WCAG22/" %>.</p>

    <h2 class="govuk-heading-m">Feedback and contact information</h2>
    <p class="govuk-body">If you require an alternative method of making a subject access request to this online form, you can also make a request by email or letter. Follow the guidance set out in the  <%= govuk_link_to "Personal information charter", "https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter" %>.</p>
    <p class="govuk-body">If you have problems using this form or need additional support, email <%= t("pages.accessibility.sar_research_email_html")%>.</p>

    <h2 class="govuk-heading-m">Reporting accessibility problems with this form</h2>
    <p class="govuk-body">We're always looking to improve the accessibility of this form. If you find any problems or think we're not meeting accessibility requirements, email: <%= t("pages.accessibility.sar_research_email_html")%>.</p>

    <h2 class="govuk-heading-m">Enforcement procedure</h2>
    <p class="govuk-body">The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the 'accessibility regulations'). If you're not happy with how we respond to your complaint, contact the <%= govuk_link_to "Equality Advisory and Support Service (EASS)", "https://www.equalityadvisoryservice.com/" %>.</p>

    <h2 class="govuk-heading-m">Technical information about this form's accessibility</h2>
    <p class="govuk-body">We are committed to making this form accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.</p>

    <h3 class="govuk-heading-s">Compliance status</h3>
    <p class="govuk-body">This form is fully compliant with the <%= govuk_link_to "Web Content Accessibility Guidelines version 2.2 AA standard", "https://www.w3.org/TR/WCAG22/" %>.</p>

    <h2 class="govuk-heading-m">What we're doing to improve accessibility</h2>
    <p class="govuk-body">We review the content and performance of this site on an ongoing basis and fix any accessibility issues identified or reported to us.</p>

    <h2 class="govuk-heading-m">Preparation of this accessibility statement</h2>
    <p class="govuk-body">This statement was prepared on 30 January 2025.</p>
    <p class="govuk-body">The tests on the website were carried out by the Ministry of Justice. We completed accessibility checks on a representative sample of pages using keyboard testing and the WAVE automated testing tool.</p>
  </div>
</div>

app/views/pages/cookie_consent.html.erb
<% title t(".page_title") %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>

    <p class="govuk-body">Request for personal information puts small files (known as 'cookies') onto your device to collect information about how you browse the site.</p>
    <p class="govuk-body">Cookies are used to:</p>
    <%= govuk_list ["measure how you use the website so it can be updated and improved based on your needs"], type: :bullet %>

    <p class="govuk-body">Cookies aren't used to identify you personally.</p>
    <p class="govuk-body">You'll normally see a message on the site before we store a cookie on your device.</p>
    <p class="govuk-body">Find out <%= govuk_link_to "how to manage cookies", "https://ico.org.uk/for-the-public/online/cookies" %> from the Information Commissioners Office.</p>

    <h2 class="govuk-heading-l">Essential cookies (strictly necessary)</h2>

    <%= govuk_table do |table| %>
      <%= table.with_head do |head| %>
        <%= head.with_row do |row| %>
          <%= row.with_cell(text: "Name") %>
          <%= row.with_cell(text: "Purpose") %>
          <%= row.with_cell(text: "Expires") %>
        <% end %>

        <%= table.with_body do |body| %>
          <%= body.with_row do |row| %>
            <%= row.with_cell(header: true, text: "rpi_cookies_consent") %>
            <%= row.with_cell(text: "Saves your cookies consent settings") %>
            <%= row.with_cell(text: "1 year") %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

    <h2 class="govuk-heading-l">Analytics cookies (optional)</h2>
    <p class="govuk-body">We use Google Analytics software to collect information about how you use this tool. We do this to help make sure this tool is meeting the needs of its users and to help us make improvements. Google Analytics stores information about:</p>
    <%= govuk_list ["the pages you visit",
                    "how long you spend on each page",
                    "how you got to the tool",
                    "what you click on while you're visiting the site"], type: :bullet %>
    <p class="govuk-body">We do not collect or store your personal information (for example your name or address) so this information can't be used to identify who you are.</p>
    <p class="govuk-body">We do not allow Google to use or share our analytics data.</p>
    <p class="govuk-body">Google Analytics sets the following cookies:</p>

    <%= govuk_table do |table| %>
      <%= table.with_head do |head| %>
        <%= head.with_row do |row| %>
          <%= row.with_cell(text: "Name") %>
          <%= row.with_cell(text: "Purpose") %>
          <%= row.with_cell(text: "Expires") %>
        <% end %>

        <%= table.with_body do |body| %>
          <%= body.with_row do |row| %>
            <%= row.with_cell(header: true, text: "_ga") %>
            <%= row.with_cell(text: "Helps us count how many people visit this tool by tracking if you've visited before") %>
            <%= row.with_cell(text: "1 week") %>
          <% end %>
          <%= body.with_row do |row| %>
            <%= row.with_cell(header: true, text: "_gid") %>
            <%= row.with_cell(text: "Helps us count how many people visit this tool by tracking if you've visited before") %>
            <%= row.with_cell(text: "24 hours") %>
          <% end %>
          <%= body.with_row do |row| %>
            <%= row.with_cell(header: true, text: "_gat") %>
            <%= row.with_cell(text: "Used to manage the rate at which page view requests are made") %>
            <%= row.with_cell(text: "1 minute") %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

    <h2 class="govuk-heading-m">Change your cookie settings</h2>

    <%= form_with url: cookies_path, method: :post do |f| %>
      <%= f.govuk_radio_buttons_fieldset :consent, legend: { text: "Do you want to accept analytics cookies?" } do %>
        <%= f.govuk_radio_button :consent, ConsentCookie::ACCEPT, label: { text: 'Yes' }, checked: @consent == ConsentCookie::ACCEPT %>
        <%= f.govuk_radio_button :consent, ConsentCookie::REJECT, label: { text: 'No' }, checked: @consent == ConsentCookie::REJECT %>
      <% end %>
      <%= f.govuk_submit "Save cookie settings" %>
    <% end %>
  </div>
</div>

app/views/pages/feedback.html.erb
<p><%= govuk_link_to("Home", "/") %></p>
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l">Give feedback on Request personal information</h1>
    <h2 class="govuk-heading-m">Satisfaction survey</h2>
    <%= form_with(local: true) do |f| %>
      <%= f.govuk_collection_radio_buttons :service_satisfaction_level,
                                           [[1, 'Very satisfied'], [2, 'Satisfied'], [3, 'Neither satisfied or dissatisfied'], [4, 'Dissatisfied'], [5, 'Very dissatisfied']],
                                           :first,
                                           :last,
                                           legend: { text: 'Overall, how did you feel about the service you received today?', tag: 'h3'  } %>
      <%= f.govuk_text_area :comments, label: { text: "<strong>How could we improve this service?</strong>".html_safe },
                            hint: { text: 'Do not include any personal or financial information, for example your National Insurance or credit card numbers.' }, max_chars: 1200 %>
      <%= f.govuk_submit "Send feedback" %>
    <% end %>
  </div>
</div>

app/views/pages/homepage.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">Request personal information from the Ministry of Justice</h1>

    <p class="govuk-body">Use this service to request personal information for yourself or someone else who has given you permission to act on their behalf.</p>
    <p class="govuk-body">You have the right to access your personal information, known as a subject access request (SAR), under the Data Protection Act 2018.</p>
    <p class="govuk-body">To understand more on the data we hold about you, your rights and how to contact us about it, please read through our <%= govuk_link_to "personal information charter", "https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter" %></p>
    <p class="govuk-body">This form allows you request information held by parts of the Ministry of Justice, including the:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>Prison service - for security and NOMIS records about time spent in prison</li>
      <li>Probation service - for electronic case notes (nDelius) about time on probation</li>
      <li>Office of the Public Guardian (OPG) - for information including lasting power of attorney records</li>
      <li>Legal Aid Agency (LAA) - for information including legal aid application data</li>
    </ul>

    <h2 class="govuk-heading-m">Before you start</h2>
    <p class="govuk-body">Completing this online form should take around 5 minutes.</p>
    <p class="govuk-body">Be as specific as you can, it will help us find the information you want.</p>
    <p class="govuk-body">Once we have all the information we need to start processing your request, you should expect the results back within 30 days.</p>
    <p class="govuk-body">You will need to complete this form in one go. You cannot save and return.</p>
    <p class="govuk-body">We will only send information once, so please be careful about how you store anything you receive.</p>

    <h2 class="govuk-heading-m">What you need</h2>
    <p class="govuk-body">You will need to provide:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>photo ID and proof of address, dated in the last 6 months, for you and anyone else you're requesting information for (legal representatives do not need to provide this)</li>
      <li>a signed letter of consent, dated in the last 6 months, if you're requesting information on behalf of someone else</li>
    </ul>
    <p class="govuk-body">If you, or the person you're requesting information for, are on probation and do not have any of the ID listed, we can accept a photograph or scan of a letter signed by a probation officer on Probation service headed paper.

    <h2 class="govuk-heading-m">Do not use this form to request information documents from the courts (within HMCTS)</h2>
    <p class="govuk-body">To request personal information that might have been recorded during a court or tribunal case, you must contact the relevant court or tribunal directly.</p>
    <p class="govuk-body">Use the <%= govuk_link_to "Find a court or tribunal service", "https://www.gov.uk/find-court-tribunal" %> to find the contact details.

    <p class="govuk-body">
      <%= govuk_start_button(text: "Start now", href: new_request_path) %>
    </p>

    <h2 class="govuk-heading-m">Other ways to ask for personal information from the Ministry of Justice</h2>
    <p class="govuk-body">Under the Data Protection Act 2018, you can also <%= govuk_link_to "make a SAR by email or post", "https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter" %>.</p>
  </div>
</div>

app/views/pages/privacy.html.erb
<% title t(".page_title") %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>
    <p class="govuk-body">This privacy notice explains what the Ministry of Justice means when we talk about personal data, why we ask for this information about you and what we do with it when you use this form.</p>
    <p class="govuk-body">It also explains how we store your data, how you can get a copy of the information we've collected about you and how you can complain if you think we've done something wrong.</p>

    <h2 class="govuk-heading-m">Who manages this service</h2>
    <p class="govuk-body">This form is managed by the Ministry of Justice.</p>
    <p class="govuk-body">The information you submit will be processed by the Ministry of Justice.</p>
    <p class="govuk-body">The Ministry of Justice is the data controller for the personal data collected by this form.</p>

    <h2 class="govuk-heading-m">When we ask for personal data</h2>
    <p class="govuk-body">Whenever we ask for information about you, we promise to:</p>
    <%= govuk_list ["always let you know why we need it",
                    "ask for relevant personal information only",
                    "make sure we do not keep it longer than needed",
                    "keep your information safe and make sure nobody can access it unless authorised to do so",
                    "only share your data with other organisations for legitimate purposes",
                    "consider any request you make to correct or delete your personal data"], type: :bullet%>
    <p class="govuk-body">We also promise to make it easy for you to:</p>
    <%= govuk_list ["tell us at any time if you want us to stop storing your personal data",
                    "make a complaint to the supervisory authority"], type: :bullet%>

    <h2 class="govuk-heading-m">The personal data we collect</h2>
    <p class="govuk-body">We only collect personal data that you directly provide with your application.</p>
    <p class="govuk-body">We only collect the information we need to deliver this service to you. The personal data collected includes:</p>
    <%= govuk_list ["your name and contact details",
                    "your date of birth",
                    "any relevant identifiers (e.g. your Prison number) which may help us to find your records"], type: :bullet%>
    <p class="govuk-body">We <%= govuk_link_to "use cookies", "http://www.aboutcookies.org.uk/managing-cookies" %> to collect data that tells us about how the service is used, including:</p>
    <%= govuk_list ["your computer, phone or tablet's IP address",
                    "the region or town where you are using your computer, phone or tablet",
                    "the operating system and web browser you use"], type: :bullet%>
    <p class="govuk-body">This information is not used to identify you personally. You can find out more about what cookies we use and why on our <%= govuk_link_to "cookie page", cookies_consent_path %>.</p>

    <h2 class="govuk-heading-m">Why we collect your personal data</h2>
    <p class="govuk-body">We collect data to enable us to process and respond to your request for personal information. The processing of your personal data is necessary for identifying and sharing the personal information which you are entitled to receive as part of your request.</p>
    <p class="govuk-body">The legal basis for collecting and processing your personal data is to ensure compliance with General Data Protection Regulation (GDPR).</p>
    <p class="govuk-body">Use of the online form is voluntary. If you do not provide all the information we ask for, we may not be able to process your request.</p>
    <p class="govuk-body">Please note that transmitting information over the internet is generally not completely secure, and the Ministry of Justice can't guarantee the security of your data. Any data you transmit is at your own risk. The Ministry of Justice has procedures and security features in place to keep your data secure once we receive it.</p>

    <h2 class="govuk-heading-m">Sharing your personal data</h2>
    <p class="govuk-body">The information you provide will not be shared with any third parties.</p>
    <p class="govuk-body">We may use your contact information to ask for feedback on using the service, but only when you have given your consent for us to do so.</p>
    <p class="govuk-body">We'll never share your information with other organisations for marketing, market research or commercial purposes.</p>

    <h2 class="govuk-heading-m">Keeping your personal data</h2>
    <p class="govuk-body">To protect your personal information, any data you enter as you progress through the online form is held temporarily and securely until you submit your application, after which your application cannot be viewed or modified further online.</p>
    <p class="govuk-body">The Ministry of Justice will keep your data for up to 2 years from when we respond to and close your request.</p>
    <p class="govuk-body">All deleted data will be destroyed securely and confidentially.</p>

    <h2 class="govuk-heading-m">How we use your personal data</h2>
    <p class="govuk-body">Your online submission will be sent from the online form to the Ministry of Justice via encrypted email. The system does not retain a copy of your information.</p>
    <p class="govuk-body">Your personal data is not used in any automated decision making (a decision made solely by automated means without any human involvement) or profiling (automated processing of personal data to evaluate certain conditions about an individual).</p>

    <h2 class="govuk-heading-m">How we store your personal data</h2>
    <p class="govuk-body">The Ministry of Justice takes data security very seriously and takes every step to ensure that your data remains private and secure. All data collected by this service is stored in a secure database kept entirely within the UK.</p>
    <p class="govuk-body">Your application will only be accessible to Ministry of Justice staff who require access to process applications</p>

    <h2 class="govuk-heading-m">Your rights</h2>
    <p class="govuk-body">You have a number of rights, depending on the reason for processing your information. These include:</p>
    <%= govuk_list ["the right to have inaccuracies in your personal data corrected",
                    "the right to fill in any gaps in your personal data, including by means of a supplementary statement",
                    "the right to ask for the processing of your personal data to be restricted",
                    "the right to ask for your personal data to be deleted if there is no longer a justification for it",
                    "the right to object to automated decision making, including profiling, that has a legal or significant effect on you as an individual"], type: :bullet%>
    <p class="govuk-body">If you want to request any of these, email <a href='mailto:data.access@justice.gov.uk'>data.access@justice.gov.uk</a> or send your request by post to:</p>
    <ul class="govuk-list address">
      <li>Disclosure Team</li>
      <li>Post point 10.25</li>
      <li>102 Petty France</li>
      <li>London</li>
      <li>SW1H 9AJ</li>
    </ul>

    <h2 class="govuk-heading-m">Getting more information</h2>
    <p class="govuk-body">You can get more details on:</p>
    <%= govuk_list ["agreements we have with other organisations for sharing information",
                    "when we can pass on personal information without telling you, for example, to help with the prevention or detection of crime or to produce anonymised statistics",
                    "instructions we give to staff on how to collect, use or delete your personal information",
                    "how we check that the information we have is accurate and up-to-date",
                    "how to make a complaint"], type: :bullet%>
    <p class="govuk-body">For more information, please contact the Ministry of Justice data protection officer at:</p>
    <ul class="govuk-list address">
      <li>The Data Protection Officer</li>
      <li>Ministry of Justice</li>
      <li>10 South Colonnade</li>
      <li>Canary Wharf</li>
      <li>E14 4PU</li>
    </ul>
    <p class="govuk-body">Email: <a href='mailto:dpo@justice.gov.uk'>dpo@justice.gov.uk</a></p>

    <h2 class="govuk-heading-m">Making a complaint</h2>
    <p class="govuk-body">When we ask you for information, we will keep to the law. If you think that your information has not been handled correctly, you can contact the <%= govuk_link_to "Information Commissioner", "https://ico.org.uk/"%> for independent advice about data protection on the address below:</p>
     <ul class="govuk-list address">
      <li>Information Commissioner's Office</li>
      <li>Wycliffe House</li>
      <li>Water Lane</li>
      <li>Wilmslow</li>
      <li>Cheshire</li>
      <li>SK9 5AF</li>
    </ul>
    <p class="govuk-body">Telephone: 0303 123 1113</a></p>
  </div>
</div>